Getting into new list or existing list after add

diff --git a/bin/deploy-getforge b/bin/deploy-getforge
--- a/bin/deploy-getforge
+++ b/bin/deploy-getforge
@@ -6,6 +6,14 @@ COL_RESET=$ESC_SEQ"39;49;00m"
 COL_RED=$ESC_SEQ"31;01m"
 COL_GREEN=$ESC_SEQ"32;01m"
 
+check_git_result () {
+   if [[ $? -ne 0 ]]; then
+      echo -en "${COL_RED}git failed!${COL_RESET}\n"
+      popd
+      exit 1
+   fi
+}
+
 # Execute build
 npm run build
 
@@ -18,25 +26,18 @@ fi
 # Build succeded, pushing
 echo -e "Build succeded, pushing to getforge"
 
-pushd ./build 
+pushd ./build
+
 git add --all . 
+check_git_result
+
 git ci -m "Another build $(date +"%y-%m-%d-%r")"
-if [[ $? -ne 0 ]]; then
-   echo -en "${COL_RED}git failed!${COL_RESET}\n"
-   popd
-   exit 1
-fi
-if [[ $? -ne 0 ]]; then
-   echo -en "${COL_RED}git failed!${COL_RESET}\n"
-   popd
-   exit 1
-fi
+check_git_result
+
 git push origin master
+check_git_result
+
 popd
-if [[ $? -ne 0 ]]; then
-   echo -en "${COL_RED}git failed!${COL_RESET}\n"
-   exit 1
-fi
 
 echo -e "${COL_GREEN}Push succeded.${COL_RESET}"
 
